In [1]:
import numpy as np

In [3]:
array_1 = np.arange(1,31)

In [5]:
# Now apply a numpy funcitons
# First function
array_1.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
# Second function
np.argmax(array_1)

29

In [8]:
# Third function
np.argmin(array_1)

0

In [9]:
# Fourth function
np.argsort(array_1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [12]:
# Fifth function
array_1.shape

(30,)

In [13]:
# Sixth function
array_1.dtype

dtype('int32')

In [14]:
# Seveth function
array_1.size

30

In [15]:
# Eigth function
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# Ninth function
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Tenth function
np.full((3,3),12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [19]:
np.full_like(array_1,4).reshape(6,5)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])