In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\Moosa-Computers\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [7]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
# Create numpy array
a = np.array([1,2,3])
display(a)
print(a)

array([1, 2, 3])

[1 2 3]


In [11]:
# Functions of numpy
display(np.zeros(10))
display(np.ones(10))
display(np.empty(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.linspace(1,2,1)

array([1.])

In [16]:
np.ones((10,10)),dtype="str"

SyntaxError: cannot assign to function call (138139346.py, line 1)