In [11]:
import numpy as np

In [7]:
a = np.arange(4*4).reshape(4,4)
display(a)

b = np.arange(4*4).reshape(4,4)**2
display(b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [8]:
np.maximum(a,b)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [9]:
np.minimum(a,b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
c = np.arange(2*2)
display(c)
display(c.reshape(2,2)) # Temporary update
display(c)
c.shape = (2,2) # Update permenanantly
display(c)

array([0, 1, 2, 3])

array([[0, 1],
       [2, 3]])

array([0, 1, 2, 3])

array([[0, 1],
       [2, 3]])

In [21]:
a = np.arange(3*3).reshape((3,3))
display(a)

display(a.T)
display(a)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# Flatten()
display(a.flatten())

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# For help
help(max)
max?

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [9]:
ubl_database = np.arange(1,30)
sbp = np.array([20,2,26,7,1000,5000,3,25000])

display(ubl_database)
display(sbp)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

array([   20,     2,    26,     7,  1000,  5000,     3, 25000])

In [11]:
emp = []
for i in sbp:
    if i in ubl_database:
        print(i)
        emp.append(i)
emp

20
2
26
7
3


[20, 2, 26, 7, 3]

In [5]:
# For checking two arrays values present or not
np.in1d(sbp,ubl_database)

array([ True,  True,  True,  True, False, False,  True, False])

In [10]:
# Get present value
sbp[np.in1d(sbp,ubl_database)]

array([20,  2, 26,  7,  3])

In [15]:
a = np.array([3,4,657,7,5,32,21])
sbp = np.array([20,2,26,7,1000,5000,3,25000])
# sbp[np.in1d(sbp,a)]
np.in1d(sbp,a)

array([False, False, False,  True, False, False,  True, False])

## Pandas

In [1]:
import pandas as pd

In [2]:
a = [1,2,3,4]
a1 = pd.Series(a)
print(a1)

0    1
1    2
2    3
3    4
dtype: int64


In [4]:
a = pd.date_range("2023-01-01","2023-02-05")

In [5]:
a

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05'],
              dtype='datetime64[ns]', freq='D')

In [9]:
# Date time                   # hours  , number of data or rows
a = pd.date_range("2023-01-01",freq="H",periods=36)
print(a)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 01:00:00',
               '2023-01-01 02:00:00', '2023-01-01 03:00:00',
               '2023-01-01 04:00:00', '2023-01-01 05:00:00',
               '2023-01-01 06:00:00', '2023-01-01 07:00:00',
               '2023-01-01 08:00:00', '2023-01-01 09:00:00',
               '2023-01-01 10:00:00', '2023-01-01 11:00:00',
               '2023-01-01 12:00:00', '2023-01-01 13:00:00',
               '2023-01-01 14:00:00', '2023-01-01 15:00:00',
               '2023-01-01 16:00:00', '2023-01-01 17:00:00',
               '2023-01-01 18:00:00', '2023-01-01 19:00:00',
               '2023-01-01 20:00:00', '2023-01-01 21:00:00',
               '2023-01-01 22:00:00', '2023-01-01 23:00:00',
               '2023-01-02 00:00:00', '2023-01-02 01:00:00',
               '2023-01-02 02:00:00', '2023-01-02 03:00:00',
               '2023-01-02 04:00:00', '2023-01-02 05:00:00',
               '2023-01-02 06:00:00', '2023-01-02 07:00:00',
               '2023-01-

In [12]:
arr = pd.DataFrame(np.arange(1,31).reshape(6,5))

In [17]:
arr = pd.DataFrame(np.arange(6*6).reshape(6,6))
display(arr)

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35